### ISSUE TITLE
Can't resolve 'howler' or similar module

### ISSUE THREAD

**Issue by Sickmannnnnn** [jeffreywallphd/OpenFinAL#109]
**Describe the bug**
The terminal cannot resolve a specific module, in the case it was the howler module. Solution is included at the bottom.

**To Reproduce**
1. Run npm start

**Expected behavior**
Run npm start and the application successfully opens.

**Screenshots**

![image](https://github.com/jeffreywallphd/AutoProphet/assets/113903157/858d628f-9160-4b41-ae13-f17a51fc0514)

**Desktop:**
 - OS: Windows
 - Browser: Electron
 - Browser Version: Current version

***Solution:***
This problem can be solved by running npm install
![image](https://github.com/jeffreywallphd/AutoProphet/assets/113903157/867d8ba2-df50-461a-bc8e-5301e99b4bfc)

**Comment by jeffreywallphd** [comment]
This was only problematic for students this semester because it was not originally included in some student's local repositories and they forgot to run npm install again. Now that it is on the main repository, future students will not encounter this error because they will start with a repository that includes it.
