### ISSUE TITLE
Time Series Chart Bug When SEC Data Loads

### ISSUE THREAD

**Issue by jeffreywallphd** [jeffreywallphd/OpenFinAL#46]
The TimeSeriesChart loads fine when you first search for a stock. Intermittently, the chart renders correctly when clicking a different time interval. However, as soon as the SEC data loads, the chart displays, but the time series renders incorrectly. It may be that the y-axis is changing or that the data is altered by the functions that retrieve the SEC data in TickerSearchBar.

**Comment by jeffreywallphd** [comment]
Update, the bug causes the y-axis the default to a lower value. This causes the higher values in the time series to be cut off. The first place to look will be the assignment of the minPrice and maxPrice state properties.

**Comment by SRuss76** [comment]
Understood. I will try to tackle this bug.

**Comment by SRuss76** [comment]
Update: I am pretty sure the bug is due to the speed of props being changed and the way async functions are waited on. The fetchSecData function always receives null props when trying to set min and max values. In the linked branch, I changed prop setting in the fetchSecData function from using the old props to using the actual data and it seems to fix the issue.

**Comment by jeffreywallphd** [comment]
Sounds good. Thanks for working on this! Please submit the pull request with your changes as soon as you are ready.

**Comment by jdwallMTU** [comment]
Thanks for your work on this @SRuss76. I am closing this issue per the fix you implemented. Nice work!!
